services:
  fraud-api:
    build: .
    container_name: fraud-api

    ports:
      - "8000:8000"

    environment:
      DB_NAME: fraud_platform
      DB_USER: postgres
      DB_PASSWORD: google
      DB_HOST: postgres
      DB_PORT: 5432

    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: fraud-postgres

    environment:
      POSTGRES_DB: fraud_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: google

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: